config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('profile/', include('user_panel.urls')),
    path('product/', include('product.urls')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path  
from . import views


app_name = 'home'
urlpatterns = [
        path('', views.homeView.as_view(), name='home'),
]

product/urls.py
from django.urls import path, re_path
from . import views


app_name = 'product'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('cat/<cat_id>', views.ProductListView.as_view(), name='product_cat_list'),
    path('filter/', views.ProductListView.as_view(), name='product_filter'),
    re_path(r'detail-product/(?P<slug>[-\w]+)', views.ProductDetailView.as_view(), name='product_detail'),
]

product/models.py
from django.db import models


class ProductCategory(models.Model):
    title = models.CharField(max_length=200, db_index=True, unique=True, verbose_name='عنوان دسته بندی')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, verbose_name='دسته والد',related_name='sub_cat' , null=True, blank=True)
    status = models.BooleanField(verbose_name= 'فعال / غیرفعال', default=True)
    is_delete = models.BooleanField(default=False, verbose_name='حذف شده / نشده')

    class Meta:
        verbose_name = 'دسته بندی محصول'
        verbose_name_plural = 'دسته بندی محصولات'

    def __str__(self):
        return self.title
    
class ProductBrand(models.Model):
    title = models.CharField(max_length=300, db_index=True, unique=True, verbose_name='عنوان برند')
    status = models.BooleanField(default=True, verbose_name='فعال / غیر فعال')
    image = models.ImageField(upload_to='images/brands',blank=True, null=True, verbose_name='تصویر برند')   
    
    class Meta:
        verbose_name =  'برند'
        verbose_name_plural = 'برند ها'
        
    def __str__(self):
        return self.title
        


class Product(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان محصول')
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='category', verbose_name='دسته بندی')
    description = models.TextField(verbose_name='توضیحات محصول')
    image = models.ImageField(upload_to='images/products', blank=True, null=True, verbose_name='تصویر محصول')
    brand = models.ForeignKey(ProductBrand, on_delete=models.CASCADE, related_name='brand', verbose_name='برند', null=True, blank=True)
    price = models.IntegerField(verbose_name='قیمت')
    status = models.BooleanField(default=True, verbose_name='وضعیت')
    slug = models.SlugField(default="", null=False, blank=True, db_index=True, unique=True, max_length=200,
                            allow_unicode=True, verbose_name='عنوان در url')
    is_delete = models.BooleanField(default=False, verbose_name='حذف شده/ نشده')

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return self.title


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE , verbose_name="محصول")
    image = models.ImageField(upload_to='images/product_gallery', verbose_name="تصویر")

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name = "تصویر گالری"
        verbose_name_plural = "گالری تصاویر"

product/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product, ProductGallery, ProductCategory, ProductBrand


class ProductListView(ListView):
    template_name = 'product/product_list.html'
    model = Product
    paginate_by = 4
    context_object_name = 'products'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = ProductCategory.objects.filter(status=True, is_delete=False, parent=None)
        context["brands"] = ProductBrand.objects.filter(status=True)
        return context
    
    def get_queryset(self):
        query = super().get_queryset()
        category = self.kwargs.get('cat_id') 
        request = self.request   
        brands = request.GET.get('brands')
        start_price = request.GET.get('start_price')
        end_price = request.GET.get('end_price')
        if category is not None:
            query = query.filter(category__id__iexact=category)
        if brands is not None:
            query = query.filter(brand__id__iexact=brands) 
        if start_price:
            query = query.filter(price__gte=start_price)  
        if end_price:
            query = query.filter(price__lte=end_price)          
        return query
    
    
    
class ProductDetailView(DetailView):
    template_name = 'product/product_detail.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        loaded_product = self.object
        context['product_galleries'] = ProductGallery.objects.filter(product_id=loaded_product.id).all()
        return context
  
  
    

product/templates/product/includes/sidebar.html
<aside id="sidebar" class="sidebar col-md-3">
    <section class="content-wrapper bg-white p-3 rounded-2 mb-3">
        <!-- start sidebar nav-->
        <section class="sidebar-nav">
            <section class="sidebar-nav-item">
                {% for category in categories %}
                  <span class="sidebar-nav-item-title">
                   {{ category.title }}
                    {% if category.sub_cat.all %}
                      <i class="fa fa-angle-left"></i>
                    {% endif %}  
                  </span>
                  {% if category.sub_cat %}
                    {% include 'product/includes/sub_categories.html' with sub_categories=category.sub_cat.all %}
                  {% endif %} 
                {% endfor %}     
            </section> 
        </section>
        <!--end sidebar nav-->
    </section>
    <form action="{% url 'product:product_filter' %}" method="get">
        <section class="content-wrapper bg-white p-3 rounded-2 mb-3">
            <section class="content-header mb-3">
                <section class="d-flex justify-content-between align-items-center">
                    <h2 class="content-header-title content-header-title-small">
                        برند
                    </h2>
                    <section class="content-header-link">
                        <!--<a href="#">مشاهده همه</a>-->
                    </section>
                </section>
            </section>
            <section class="sidebar-brand-wrapper mb-3">          
                {% for brand in brands %}
                <section class="form-check sidebar-brand-item">
                        <input class="form-check-input" type="checkbox" name="brands" value="{{ brand.id }}" id="{{ brand.id }}">
                        <label class="form-check-label d-flex justify-content-between" for="{{ brand.id }}">
                            <span>{{ brand.title }}</span>
                        </label>
                </section> 
                {% endfor %} 
            </section>
            <section class="content-header mb-4">
                <section class="d-flex justify-content-between align-items-center">
                    <h2 class="content-header-title content-header-title-small">
                        محدوده قیمت
                    </h2>
                    <section class="content-header-link">
                        <!--<a href="#">مشاهده همه</a>-->
                    </section>
                </section>
            </section>
            <section class="sidebar-price-range d-flex justify-content-between mb-4">
                <section class="p-1"><input type="text" name="start_price" placeholder="قیمت از ..."></section>
                <section class="p-1"><input type="text" name="end_price" placeholder="قیمت تا ..."></section>
            </section>

            <section class="sidebar-filter-btn d-grid gap-2">
                <button class="btn btn-danger" type="submit">اعمال فیلتر</button>
            </section>
        </section>
    </form>
</aside>

product/templates/product/includes/sub_categories.html
<section class="sidebar-nav-sub-wrapper py-1 px-2">
    <section class="sidebar-nav-sub-item">
      {% for category in sub_categories %}
           
           {% if category.sub_cat.all %}
                <span class="sidebar-nav-sub-item-title">
                    {{ category.title }} 
                    <i class="fa fa-angle-left"></i>
                </span>
            {% else %}
                <span class="sidebar-nav-sub-item-title">
                  <a href="{% url 'product:product_cat_list' cat_id=category.id %}" class="d-inline">
                    {{ category.title }}
                   </a>
                </span>
           {% endif %} 
            {% if category.sub_cat.all %}
               {% include 'product/includes/sub_categories.html' with sub_categories=category.sub_cat.all %}
            {% endif %} 
       {% endfor %} 
    </section>
</section>