config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('profile/', include('user_panel.urls')),
    path('product/', include('product.urls')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path  
from . import views


app_name = 'home'
urlpatterns = [
        path('', views.homeView.as_view(), name='home'),
]

user_panel/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'user_panel'
urlpatterns = [
     path('index', login_required(views.ProfileView.as_view()), name='profile'),
     path('edit-profile', login_required(views.EditProfileView.as_view()), name='edit_profile'),
     path('change-password', login_required(views.ChangePasswordView.as_view()), name='change_password')

]

user_panel/models.py
from django.db import models

user_panel/forms.py
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from account.models import User


def start_with_0(value):
    if value[0] != '0':
        raise forms.ValidationError("شماره موبایل باید با صفر شروع شود!")


class ChangeProfile(forms.ModelForm):
    class Meta:
        model = User
        fields = ('fullname', 'phone', 'email', 'avatar')
    fullname = forms.CharField(label='نام و نام خانوادگی',
                               required=False,
                               widget=forms.TextInput(attrs={'class': 'form-control'}),
                               validators=[validators.MaxLengthValidator(50)]
                               )
    phone = forms.CharField(label='شماره تلفن', 
                            widget=forms.TextInput(attrs={'class': 'form-control'}),
                            validators=[validators.MaxLengthValidator(11), start_with_0])
    email = forms.CharField(
        label='ایمیل',
        widget=forms.EmailInput(attrs={'class': 'form-control'}), 
        validators=[validators.MaxLengthValidator(100),
                    validators.EmailValidator]
    )
 
    avatar = forms.ImageField(label='تصویر کاربر',
                              required=False,
                              widget=forms.FileInput)



class ChangePasswordForm(forms.Form):
    password = forms.CharField(
        label='کلمه عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        validators=[validators.MaxLengthValidator(100)])
    confirm_password = forms.CharField(
        label='تکرار کلمه عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        validators=[validators.MaxLengthValidator(100)]
       )
    
    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if confirm_password == password:
            return confirm_password 
        raise ValidationError('کلمه عبور و تکرار کلمه عبور با هم مغایرت دارند!')


   

user_panel/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from .forms import ChangeProfile, ChangePasswordForm
from account.models import User
import sweetify


class ProfileView(View):
    def get(self, request):
        return render(request, 'user_panel/my_profile.html')


class EditProfileView(View):
    def get(self, request):
        intial_user = {
            'fullname': request.user.fullname,
            'email': request.user.email,
            'phone': request.user.phone,
            'avatar': request.user.avatar,
        }
        form = ChangeProfile(request.POST or None, initial=intial_user)
        context = {
            'form': form
        }
        return render(request, 'user_panel/edit_profile.html', context)

    # def post(self, request):
    #     form = ChangeProfile(request.POST, request.FILES)
    #     user = User.objects.filter(id=request.user.id).first()
    #     user_fullname = user.fullname
    #     user_email = user.email
    #     user_phone = user.phone

    #     if form.is_valid():
    #         cd = form.cleaned_data
    #         fullname_form = cd.get('fullname')
    #         email_form = cd.get('email')
    #         phone_form = cd.get('phone')
    #         avatar_form = cd.get('avatar')

    #         if fullname_form != user_fullname:
    #             user.fullname = fullname_form

    #         if email_form != user_email:
    #             users_check = User.objects.filter(email__iexact=email_form).exists()
    #             if users_check:
    #                 form.add_error('email', 'ایمیل وارد شده تکراری میباشد!')
    #                 return render(request, 'user_panel/edit_profile.html', {'form': form})
    #             user.email = email_form

    #         if phone_form != user_phone:
    #             users_check = User.objects.filter(phone__iexact=phone_form).exists()
    #             if users_check:
    #                 form.add_error('phone', 'شماره وارد شده تکراری میباشد!')
    #                 return render(request, 'user_panel/edit_profile.html', {'form': form})
    #             user.phone = phone_form
    #             user.phone_active_code = None
    #         if avatar_form:
    #             user.avatar = avatar_form
    #         user.save()
    #         sweetify.success(request, 'اطلاعات مورد نظر با موفقیت برروزرسانی گردید')
    #         return render(request, 'user_panel/my_profile.html')
    #     else:
    #         form.non_field_errors()
    #     return render(request, 'user_panel/edit_profile.html', {'form': form})
    
    def post(self,request):
        form = ChangeProfile(instance=request.user,data=request.POST, files=request.FILES)
        if form.is_valid():     
            form.save()
            sweetify.success(request, 'اطلاعات مورد نظر با موفقیت برروزرسانی گردید')
        else:
            form.non_field_errors()
        return render(request, 'user_panel/edit_profile.html', {'form': form})    
            


class ChangePasswordView(View):
    def get(self, request):
        form = ChangePasswordForm()
        return render(request, 'user_panel/change_password.html', {'form': form})

    def post(self, request):
        form = ChangePasswordForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            user_id = request.user.id
            user = User.objects.get(id=user_id)
            user.set_password(cd.get('password'))
            user.save()
            sweetify.success(request, 'کلمه عبور با موفقیت بروزرسانی گردید')
            return redirect(reverse('account:login_user')+"?next="+ request.path)
        return render(request , 'user_panel/change_password.html', {'form': form})

user_panel/templates/user_panel/change_password.html
{% extends 'master.html' %}
{% block title %}
    تغییرکلمه عبور
{% endblock %}

{% block content %}
    <section class="row">
        {% include 'user_panel/includes/sidebar.html' %}
        <main id="main-body" class="main-body col-md-9">
            <section class="content-wrapper bg-white p-3 rounded-2 mb-2">
                <section class="content-header mb-4">
                    <section class="d-flex justify-content-between align-items-center">
                        <h2 class="content-header-title">
                            <span>اطلاعات حساب</span>
                        </h2>
                        <section class="content-header-link">
                            <!--<a href="#">مشاهده همه</a>-->
                        </section>
                    </section>
                </section>
                {% for error in form.none_field_errors %}
                    <p class='alert alert-danger'>{{ error }}</p>
                {% endfor %}
                <form method="post">
                    {% csrf_token %}
                    <section class='login-title mb-3'>{{ form.password.label_tag }}</section>
                    <section class="login-input-text mb-3"> {{ form.password }}</section>
                    {% for error in form.password.errors %}
                        <p class="alert alert-danger">{{ error }}</p>
                    {% endfor %}

                    <section class='login-title mb-3'>{{ form.confirm_password.label_tag }}</section>
                    <section class="login-input-text mb-3"> {{ form.confirm_password }}</section>
                    {% for error in form.confirm_password.errors %}
                        <p class="alert alert-danger">{{ error }}</p>
                    {% endfor %}

                    <section class="col-3 ms-auto py-2">

                        <section class="field-value overflow-auto d-grid">
                            <button type="submit" class="btn btn-info btn-block">تغییر کلمه عبور</button>
                        </section>
                    </section>
                </form>

            </section>
        </main>
    </section>

{% endblock %}

user_panel/templates/user_panel/edit_profile.html
{% extends 'master.html' %}
{% load thumbnail %}
{% block title %}ویرایش حساب کاربری{% endblock %}

{% block content %}

    <section class="row">

        {% include 'user_panel/includes/sidebar.html' %}
        <main id="main-body" class="main-body col-md-9">
            <section class="content-wrapper bg-white p-3 rounded-2 mb-2">

                <!-- start vontent header -->
                <section class="content-header mb-4">
                    <section class="d-flex justify-content-between align-items-center">
                        <h2 class="content-header-title">
                            <span>ویرایش حساب</span>
                        </h2>
                        <section class="content-header-link">
                            <!--<a href="#">مشاهده همه</a>-->
                        </section>
                    </section>
                </section>
                <!-- end vontent header -->
                <form method="post" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <section class="row">
                        {% for error in form.none_field_errors %}
                            <p class='alert alert-danger mt-2'>{{ error }}</p>
                        {% endfor %}
                        <section class="col-6 my-2 py-2">
                            <section class="field-title">{{ form.fullname.label_tag }}  </section>
                            <section class="field-value overflow-auto">{{ form.fullname }}</section>
                            {% for error in form.fullname.errors %}
                                <p class="alert alert-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </section>
                        <section class="col-6  my-2 py-2">
                            <section class="field-title"> {{ form.phone.label_tag }} </section>
                            <section class="field-value overflow-auto">{{ form.phone }}</section>
                            {% for error in form.phone.errors %}
                                  <p class="alert alert-danger mt-2">{{ error }}</p>
                             {% endfor %}
                        </section>

                        <section class="col-6 my-2 py-2">
                            <section class="field-title">{{ form.email.label_tag }}</section>
                            <section class="field-value overflow-auto">{{ form.email }}</section>
                            {% for error in form.email.errors %}
                                  <p class="alert alert-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </section>

                        <section class="col-6 my-2 py-2">
                            <section class="field-title my-3">{{ form.avatar.label_tag }} </section>
                            <section class="field-value overflow-auto">
                                {{ form.avatar }}
                            </section>
                            {% for error in form.avatar.errors %}
                                  <p class="alert alert-danger mt-2">{{ error }}</p>
                            {% endfor %}
                        </section>

                        <section class="col-9 my-2 py-2"></section>
                        <section class="col-3 my-2 py-2">

                            <section class="field-value overflow-auto d-grid">
                                <button type="submit" class="btn btn-info btn-block">ارسال</button>
                            </section>
                        </section>

                    </section>
            </form>
            </section>
        </main>
    </section>
{% endblock %}

user_panel/templates/user_panel/my_profile.html
{% extends 'master.html' %}
{% load thumbnail %}

{% block title %} حساب کاربری{% endblock %}
{% block content %}
<section class="row">
    {% include 'user_panel/includes/sidebar.html' %}
    <main id="main-body" class="main-body col-md-9">
        <section class="content-wrapper bg-white p-3 rounded-2 mb-2">
            <!-- start vontent header -->
            <section class="content-header mb-4">
                <section class="d-flex justify-content-between align-items-center">
                    <h2 class="content-header-title">
                        <span>اطلاعات حساب</span>
                    </h2>
                    <section class="content-header-link">
                        <!--<a href="#">مشاهده همه</a>-->
                    </section>
                </section>
            </section>
            <!-- end vontent header -->
            <section class="d-flex justify-content-end my-4">
                <a class="btn btn-link btn-sm text-info text-decoration-none mx-1" href="{% url 'user_panel:edit_profile' %}"><i class="fa fa-edit px-1"></i>ویرایش حساب</a>
            </section>
            <section class="row">
                <section class="col-6 border-bottom mb-2 py-2">
                    <section class="field-title">نام و نام خانوادگی</section>
                    <section class="field-value overflow-auto">{{ request.user.fullname }}</section>
                </section>

         
                <section class="col-6 border-bottom my-2 py-2">
                    <section class="field-title">شماره تلفن همراه</section>
                    <section class="field-value overflow-auto">{{ request.user.phone }}</section>
                </section>

                <section class="col-6 border-bottom my-2 py-2">
                    <section class="field-title">ایمیل</section>
                    <section class="field-value overflow-auto">{{ request.user.email }}</section>
                </section>

              
                <section class="col-6 my-2 py-2">
                    <section class="field-title">کلمه عبور</section>
                    <section class="field-value overflow-auto">
                        <a href="{% url 'user_panel:change_password' %}" class="btn btn-link btn-sm text-info text-decoration-none mx-1">
                                   ویرایش کلمه عبور</a>
                    </section>
                </section>
                <section class="col-6 my-3 py-3">
                    <section class="field-title my-3">تصویر </section>
                    <section class="field-value overflow-auto">
                        {% thumbnail request.user.avatar "70x50" crop="center" as im %}
                          <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% endthumbnail %}  
                    </section>
                </section>
            </section>
        </section>
    </main>
</section>
{% endblock  %}