config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('profile/', include('user_panel.urls')),
    path('product/', include('product.urls')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path  
from . import views


app_name = 'home'
urlpatterns = [
        path('', views.homeView.as_view(), name='home'),
]

product/urls.py
from django.urls import path, re_path
from . import views


app_name = 'product'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('cat/<cat_id>', views.ProductListView.as_view(), name='product_cat_list'),
    path('filter/', views.ProductListView.as_view(), name='product_filter'),
    re_path(r'detail-product/(?P<slug>[-\w]+)', views.ProductDetailView.as_view(), name='product_detail'),
]

product/models.py
from django.db import models


class ProductCategory(models.Model):
    title = models.CharField(max_length=200, db_index=True, unique=True, verbose_name='عنوان دسته بندی')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, verbose_name='دسته والد',related_name='sub_cat' , null=True, blank=True)
    status = models.BooleanField(verbose_name= 'فعال / غیرفعال', default=True)
    is_delete = models.BooleanField(default=False, verbose_name='حذف شده / نشده')

    class Meta:
        verbose_name = 'دسته بندی محصول'
        verbose_name_plural = 'دسته بندی محصولات'

    def __str__(self):
        return self.title
    
class ProductBrand(models.Model):
    title = models.CharField(max_length=300, db_index=True, unique=True, verbose_name='عنوان برند')
    status = models.BooleanField(default=True, verbose_name='فعال / غیر فعال')
    image = models.ImageField(upload_to='images/brands',blank=True, null=True, verbose_name='تصویر برند')   
    
    class Meta:
        verbose_name =  'برند'
        verbose_name_plural = 'برند ها'
        
    def __str__(self):
        return self.title
        


class Product(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان محصول')
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='category', verbose_name='دسته بندی')
    description = models.TextField(verbose_name='توضیحات محصول')
    image = models.ImageField(upload_to='images/products', blank=True, null=True, verbose_name='تصویر محصول')
    brand = models.ForeignKey(ProductBrand, on_delete=models.CASCADE, related_name='brand', verbose_name='برند', null=True, blank=True)
    price = models.IntegerField(verbose_name='قیمت')
    status = models.BooleanField(default=True, verbose_name='وضعیت')
    slug = models.SlugField(default="", null=False, blank=True, db_index=True, unique=True, max_length=200,
                            allow_unicode=True, verbose_name='عنوان در url')
    is_delete = models.BooleanField(default=False, verbose_name='حذف شده/ نشده')

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return self.title


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE , verbose_name="محصول")
    image = models.ImageField(upload_to='images/product_gallery', verbose_name="تصویر")

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name = "تصویر گالری"
        verbose_name_plural = "گالری تصاویر"

product/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product, ProductGallery, ProductCategory, ProductBrand


class ProductListView(ListView):
    template_name = 'product/product_list.html'
    model = Product
    paginate_by = 4
    context_object_name = 'products'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = ProductCategory.objects.filter(status=True, is_delete=False, parent=None)
        context["brands"] = ProductBrand.objects.filter(status=True)
        return context
    
    def get_queryset(self):
        query = super().get_queryset()
        category = self.kwargs.get('cat_id') 
        request = self.request   
        brands = request.GET.get('brands')
        start_price = request.GET.get('start_price')
        end_price = request.GET.get('end_price')
        if category is not None:
            query = query.filter(category__id__iexact=category)
        if brands is not None:
            query = query.filter(brand__id__iexact=brands) 
        if start_price:
            query = query.filter(price__gte=start_price)  
        if end_price:
            query = query.filter(price__lte=end_price)          
        return query
    
    
    
class ProductDetailView(DetailView):
    template_name = 'product/product_detail.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        loaded_product = self.object
        context['product_galleries'] = ProductGallery.objects.filter(product_id=loaded_product.id).all()
        return context
  
  
    

product/templates/product/product_list.html
{% extends 'master.html' %}
{% load poll_extras %}
{% load thumbnail %}

{% block title %}لیست محصولات{% endblock %}

{% block content %}


<section class="row">
    {% include 'product/includes/sidebar.html' %}
    <main id="main-body" class="main-body col-md-9">
        <section class="content-wrapper bg-white p-3 rounded-2 mb-2">
            
            <section class="sort ">
                <span>مرتب سازی بر اساس : </span>
                <button class="btn btn-info btn-sm px-1 py-0" type="button">جدیدترین</button>
                <button class="btn btn-light btn-sm px-1 py-0" type="button">محبوب ترین</button>
                <button class="btn btn-light btn-sm px-1 py-0" type="button">گران ترین</button>
                <button class="btn btn-light btn-sm px-1 py-0" type="button">ارزان ترین</button>
                <button class="btn btn-light btn-sm px-1 py-0" type="button">پربازدیدترین</button>
                <button class="btn btn-light btn-sm px-1 py-0" type="button">پرفروش ترین</button>
            </section>

            <section class="main-product-wrapper row my-4">

                {% for product in products %}
                    <section class="col-md-3 p-0">
                        <section class="product">
                            <section class="product-add-to-cart"><a href="#" data-bs-toggle="tooltip" data-bs-placement="left" title="افزودن به سبد خرید"><i class="fa fa-cart-plus"></i></a></section>
                            <section class="product-add-to-favorite"><a href="#" data-bs-toggle="tooltip" data-bs-placement="left" title="افزودن به علاقه مندی"><i class="fa fa-heart"></i></a></section>
                            <a class="product-link" href="{% url 'product:product_detail' product.slug %} ">
                                <section class="product-image">
                                
                                       <img class="" src="{{ product.image.url }}" alt="">
                                 
                                </section>
                                <section class="product-colors"></section>
                                <section class="product-name"><h3>{{ product.title  }}</h3></section>
                                <section class="product-price-wrapper">
                                    <section class="product-price">{{ product.price| three_digits_currency }} </section>
                                </section>
                            </a>
                        </section>
                    </section>
                {% endfor %}
                
               {% if page_obj.has_other_pages %}
                    <section class="col-12">
                        <section class="my-4 d-flex justify-content-center">
                            <nav>
                                <ul class="pagination">

                                    {% if page_obj.has_previous %}
                                    
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                                <span aria-hidden="true">«</span>
                                            </a>
                                        </li>

                                {% else %}
                                
                                        <li class="page-item disabled">
                                            <span class="page-link" href="#" aria-label="Previous">      
                                                <span aria-hidden="true">«</span>
                                            </span>
                                        </li>
                                
                                {% endif %}                               
                                    {% for pageNumber in paginator.page_range  %}
                                    {% if page_obj.number == pageNumber %}
                                            <li class="page-item active">
                                                <span class="page-link" >{{ pageNumber }}</span>
                                            </li>
                                    {% else %} 
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ pageNumber }}">{{ pageNumber }}</a>
                                    </li>
                                    {% endif %}
                                    {% endfor %}

                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">   
                                                <span aria-hidden="true">»</span>
                                            </a>
                                        </li> 
                                    {% else %}
                                            <li class="page-item disabled">
                                                <span class="page-link"  aria-label="Next">   
                                                    <span aria-hidden="true">»</span>
                                                </span>
                                            </li> 
                                    {% endif %}                       
                                </ul>
                            </nav>
                        </section>
                    </section>
                {% endif %}

            </section>
        </section>
    </main>
</section>
{% endblock %}